apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-deployment
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: speedtest
        image: maarham/volterra-speedtest:latest
        ports:
        - containerPort: 8080
-----------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: Speedtest
spec:
  selector:
    app: MySpeedtest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
