apiVersion: v1
kind: Service
metadata:
  name: speedtest
  annotations:
    ves.io/virtual-sites: speed-test/paris-azure
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: speedtest
